### ISSUE TITLE
Unit display name?

### ISSUE THREAD

**Issue by sffc** [tc39-transfer/proposal-intl-displaynames#34]
CLDR has display names for measurement units.  Maybe expose them through Intl.DisplayNames?

**Comment by FrankYFTang** [comment]
good point. We could do that. But this will need to reference to the Unified proposal which is not yet merged into ECMA402 and increase data size.

**Comment by FrankYFTang** [comment]
I put together a v2 repo on https://github.com/FrankYFTang/intl-displaynames-v2/ please move the future discussion there.

**Comment by FrankYFTang** [comment]
This proposal reach Stage 4 in TC39 2020 Sept meeting, therefore close this issue down and move the discussion to  https://github.com/tc39/intl-displaynames-v2/issues/12
