### ISSUE TITLE
Stage 3 review

### ISSUE THREAD

**Issue by littledan** [tc39-transfer/proposal-intl-displaynames#38]
Reviewers
-  [ ] @littledan
-  [ ] more reviewers to be found async

Editors
- [ ] @ljharb 
- [ ] @zenparsing

**Comment by littledan** [comment]
I think this proposal will be ready for Stage 3 once we address the comments on https://github.com/tc39/proposal-intl-displaynames/pull/30 and fix the issues #35, #36, #37, and #38. I will be away from work in July and August, so I will not be able to review everything about the fixes if this is proposed for stage advancement in the July meeting, but I am happy to defer to another reviewer in TC39 from here.

**Comment by bmeck** [comment]
sign me up

**Comment by ljharb** [comment]
- https://tc39.es/proposal-intl-displaynames/#sec-isvaliddayperiodcode and https://tc39.es/proposal-intl-displaynames/#sec-isvaliddatetimefieldcode need to `ToString` the `dayperiod` argument, just like the others do `ToNumber`
 - why does an undefined options need to `ObjectCreate(null)`? could `GetOption` not just `return fallback` if `options` is undefined?
 - https://tc39.es/proposal-intl-displaynames/#sec-Intl.DisplayNames.prototype.of step 4 needs an Oxford comma after "Number"

**Comment by FrankYFTang** [comment]
> * https://tc39.es/proposal-intl-displaynames/#sec-isvaliddayperiodcode and https://tc39.es/proposal-intl-displaynames/#sec-isvaliddatetimefieldcode need to `ToString` the `dayperiod` argument, just like the others do `ToNumber`

These two were removed in the spec now. We may add them back for the next version.

> * why does an undefined options need to `ObjectCreate(null)`? could `GetOption` not just `return fallback` if `options` is undefined?

Please read 
https://tc39.es/ecma402/#sec-getoption
9.2.10 GetOption ( options, property, type, values, fallback )
1. Let value be ? Get(options, property).
and
https://tc39.es/ecma262/#sec-get-o-p
7.3.1 Get ( O, P )
1. Assert: Type(O) is Object.

if O is undefined, the Type(O) is Object assertion will break.

> * https://tc39.es/proposal-intl-displaynames/#sec-Intl.DisplayNames.prototype.of step 4 needs an Oxford comma after "Number"
OK, file editorial issue https://github.com/tc39/proposal-intl-displaynames/issues/64

**Comment by FrankYFTang** [comment]
@bmeck - please review and provide your feedback. TC39 Oct meeting note mentioned
https://github.com/tc39/notes/blob/master/meetings/2019-10/october-2.md#intldisplaynames
"Conclusion/Resolution
BFS to review
Consensus for stage 3 pending above review"

So the Stage 3 are blocked by this. and therefore also block the approval for Chromium

**Comment by bmeck** [comment]
LGTM spec wise, there are a couple of README PRs outstanding it looks like though; nothing to block on

**Comment by littledan** [comment]
The proposal has reached Stage 3.
