### ISSUE TITLE
Script and variants info

### ISSUE THREAD

**Issue by rxaviers** [tc39-transfer/proposal-intl-displaynames#5]
The proposal as is includes regions, locales, and language display names. Would it include scripts and variants too?

https://github.com/unicode-cldr/cldr-localenames-modern/tree/master/main/en

--

back reference: https://github.com/brawer/proposal-intl-displaynames/issues/6

**Comment by FrankYFTang** [comment]
1. The current version already include an ofScript
2. The current version also let ofLanguage to accept unicode_language_id which include both the script and  "variant" part. 
So I will close this ticket. If you feel we should consider adding support of a method which only take the "variant" itself (not as part of an unicode_language_id) and return the display name for that given variant, could you please comment that on https://github.com/tc39/proposal-intl-displaynames/issues/8 instead? I am open to that but I like to see how other think the usage of such information before I revise the spec to include that.

Mark this close
