### ISSUE TITLE
Need to add calendar option to get different display names of type: "month", "weekday", "quarter" and "dayPeriod"

### ISSUE THREAD

**Issue by FrankYFTang** [tc39-transfer/proposal-intl-displaynames#52]
Just notice CLDR (and therefore ICU) has different display names for "month", "weekday", "quarter" and "dayPeriod" for different "calendar"

Therefore, we should
1. accept a "calendar" option in Intl.DisplayNames constructor if the type is "month", "weekday", "quarter" or "dayPeriod"
2. based on the "calendar" option, the internal fields should be set differently based on the calendar.

**Comment by sffc** [comment]
You can control the calendar via the language tag, e.g., `th-u-ca-buddhist`

However it would still be good to add a separate option since this API does use the calendar field.  This would be consistent with our general vision of parity between options bag and locale fields.
