### ISSUE TITLE
Intl.DisplayNames payload

### ISSUE THREAD

**Issue by zbraniecki** [tc39-transfer/proposal-intl-displaynames#60]
An analysis of a payload cost for SpiderMonkey to ship this API - https://bugzilla.mozilla.org/show_bug.cgi?id=1557727#c7

**Comment by sffc** [comment]
Ok, so based on that analysis, SpiderMonkey does not *already* include region display names and language display names, and therefore shipping this API requires adding that data.  Correct?

(In V8's case, they were already carrying that data, so this feature had minimal impact on binary size)

**Comment by zbraniecki** [comment]
This is correct.

**Comment by zbraniecki** [comment]
Intl.DisplayNames [landed](https://bugzilla.mozilla.org/show_bug.cgi?id=1557727) in SM.
