### ISSUE TITLE
Canonicalise language, script, and region tags

### ISSUE THREAD

**Issue by anba** [tc39-transfer/proposal-intl-displaynames#70]
Language, script, and region tags should be canonicalised, because
1. This matches how ECMA-402 works for other API.
1. ICU does this implicitly for some APIs resp. other ICU APIs require a canonicalised input to produce any result.

---

For example when `new Intl.DisplayNames("en", {type: "language"}).of("de-DD")` returns `"German (Germany)"`, for consistency we should then ensure that `new Intl.DisplayNames("en",{type: "region"}).of("DD")` returns `"Germany"`.

**Comment by FrankYFTang** [comment]
Reopen since we didn't go through the canonicalization process and also the casing statement is not correct.
