### ISSUE TITLE
Input conversion for language tags inconsistent with CanonicalizeLocaleList

### ISSUE THREAD

**Issue by anba** [tc39-transfer/proposal-intl-displaynames#71]
`Intl.DisplayNames.prototype.of` was recently (#67) changed to use plain `ToString` to convert the input. This makes `Intl.DisplayNames` inconsistent with [CanonicalizeLocaleList](https://tc39.es/ecma402/#sec-canonicalizelocalelist), which only allows `String` and `Object` inputs to avoid accepting `NaN` as `"nan"`.

```js
js> new Intl.DisplayNames("en", {type: "language"}).of(NaN)
"Min Nan Chinese"
```

But we didn't care about this case anymore when specifiying `Intl.Locale`:

```js
js> new Intl.Locale("und", {language: NaN}).toString()
"nan"
```

so maybe unconditionally calling `ToString` is okay. We should just make sure everybody is on board with this decision.

**Comment by FrankYFTang** [comment]
This proposal reach Stage 4 on 2020 Sept TC39 meeting. Move this issue to https://github.com/tc39/intl-displaynames-v2/issues/7
